import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { cwd } from "node:process";
import { svg2woff2 } from "../src/main";
import { generateCss } from "../src/svg2woff2";

const require = createRequire(import.meta.url);

// read svg files
const base_dir = path.join(path.dirname(require.resolve("@fortawesome/fontawesome-free/package.json")), "svgs/brands/");
const svg_files = ["youtube", "github", "x-twitter"];
const svgs = svg_files.map((name) => {
    const filepath = path.join(base_dir, `${name}.svg`);
    const content = readFileSync(filepath, "utf8");
    return { name, content };
});

// convert to woff2
const font_family = "hanabi generated font";
const output_file = "hf-builtin-400.woff2";
const version = "1.0";
const description = "font generated by svg2woff2";
const url = "https://github.com/osawa-naotaka/svg2woff2.git";

const woff2 = await svg2woff2(svgs, { font_family, version, description, url });
const css = generateCss(svgs, { font_family, url: output_file });

console.log(`generateWoff2(): Buffer size = ${woff2.length}`);
console.log("Generated WOFF2 Data (base64):", woff2.toString("base64"));
console.log("Generated CSS:", css);

// write to files
const output_dir = path.join(cwd(), "build");
writeFileSync(path.join(output_dir, output_file), woff2);
writeFileSync(path.join(output_dir, "font.css"), css);
