name: Build with Bun and publish to npm

on:
  push:
    branches:
      - main
      - publish

jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Build project
        run: bun run build

      - name: npm publish
        run: npm publish --provenance --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Success
        if: success()
        run: echo "✅ Publish completed successfully!"
      
      - name: Publish Failure
        if: failure()
        run: echo "❌ Publish failed!"
